---
- name: Setting exececution policy to "Unrestricted"
  ansible.windows.win_shell: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine -Force

- name: Disabling Windows Updates
  ansible.windows.win_service:
    name: wuauserv
    start_mode: disabled
    state: stopped

- name: Ensuring Windows Update is disabled
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\wuauserv
    name: Start
    data: 4
    type: dword

- name: Disabling firewall
  community.windows.win_firewall:
    state: disabled
    profiles:
    - Domain
    - Private
    - Public

- name: Disabling Defender real-time protection
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: DisableRealtimeMonitoring
    data: 1
    type: dword

- name: Disabling Defender cloud-delivered protection
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet
    name: SpynetReporting
    data: 0
    type: dword

- name: Disabling Defender automatic sample submission
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Spynet
    name: SubmitSamplesConsent
    data: 2
    type: dword

- name: Setting %SYSTEMDRIVE% fact
  set_fact:
    system_drive: C:\

- name: Adding the directory C:\ to the exclusion list
  ansible.windows.win_shell: Add-MpPreference -ExclusionPath "{{ system_drive }}" -Force

- name: Installing Choco packages
  chocolatey.chocolatey.win_chocolatey:
    name:
    - adobereader
    - firefox
    - googlechrome
    - python2
    state: present
    ignore_checksums: true

- name: Downloading get-pip.py
  ansible.windows.win_get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: C:\Windows\Temp\get-pip.py

- name: Installing Pip
  ansible.windows.win_shell: C:\Python27\python.exe get-pip.py
  args:
    chdir: C:\Windows\Temp

- name: Removing get-pip.py
  ansible.windows.win_file:
    path: C:\Windows\Temp\get-pip.py
    state: absent

- name: Installing Pillow
  ansible.windows.win_shell: C:\Python27\python.exe -m pip install Pillow==6.0.0

- name: Installing Cuckoo agent
  ansible.windows.win_copy:
    src: ../files/agent.py
    dest: C:\Users\vagrant\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\spy.pyw

- name: Enabling autologon
  community.windows.win_auto_logon:
    username: vagrant
    password: vagrant

- name: Enabling RPC
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\TerminalServer
    name: AllowRemoteRPC
    data: 1
    type: dword

- name: Enabling RPC
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    name: LocalAccountTokenFilterPolicy
    data: 1
    type: dword

- name: Setting internal network gateway for inetsim routing
  ansible.windows.win_shell: Remove-NetIPAddress 192.168.56.101 -Confirm:$false

- name: Setting internal network gateway for inetsim routing
  ansible.windows.win_shell: New-NetIPAddress -InterfaceAlias 'Ethernet 2' -IPAddress '192.168.56.101' -PrefixLength 24 -DefaultGateway '192.168.56.100'

- name: Setting DNS for inetsim routing
  ansible.windows.win_dns_client:
    adapter_names: 'Ethernet 2'
    dns_servers: 192.168.56.100

- name: Disabling probing
  ansible.windows.win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\NlaSvc\Parameters\Internet
    name: EnableActiveProbing
    data: 0
    type: dword

- name: Removing OneDrive
  ansible.windows.win_package:
    path: C:\Windows\SysWOW64\OneDriveSetup.exe
    product_id: OneDrive
    arguments: /uninstall
    state: absent

- name: Rebooting machine to make changes take effect
  ansible.windows.win_reboot:
